version: "3.1"

services:
  svdesk-v2-dev:
    image: harbor-dev.itsec.md/servicedesk_v2/servicedesk_v2-dev:latest
    restart: always
    container_name: dev-svdesk-v2-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "Logging:LogLevel:Default=Information"
      - "Logging:LogLevel:Microsoft.AspNetCore=Warning"
      - "MPassSamlOptions:SamlRequestIssuer=https://semneaza.md"
      - "MPassSamlOptions:ServiceCertificatePath=App_Data/Certificates/semneaza.md.pfx"
      - "MPassSamlOptions:ServiceCertificatePassword=11111111"
      - "MPassSamlOptions:IdentityProviderCertificatePath=App_Data/Certificates/testmpass.cer"
      - "MPassSamlOptions:SamlLoginDestination=https://mpass.staging.egov.md/login/saml"
      - "MPassSamlOptions:SamlLogoutDestination=https://mpass.staging.egov.md/logout/saml"
      - "MPassSamlOptions:ServiceRootUrl=https://dev-sd.itsec.md"
      - "MPassSamlOptions:LogoutResponsePath=/mpass-logout-callback"
      - "MPassSamlOptions:SamlMessageTimeout=00:10:00"
      - "ConnectionStrings:DefaultConnection=${DB_CONNECTION_STRING}"
      - "SmtpSettings:Host=smtp.stisc.gov.md"
      - "SmtpSettings:Port=587"
      - "SmtpSettings:Username=suport-test@stisc.gov.md"
      - "SmtpSettings:Password=WiTywpa9sbN24EDPM"
      - "SmtpSettings:From=suport-test@stisc.gov.md"
      - "SmtpSettings:DebugEmail=suport-test@stisc.gov.md"
    entrypoint: sh -c "echo \"${DB_CONNECTION_STRING}\" > /app/App_Data/dbconfig.txt && ./ServiceDesck"
    ports:
      - "8080:8080"